import { CardTypeStyles, CardTypeStyle } from '../types/card';

const defaultStyle: CardTypeStyle = {
  titlePosition: {
    top: '8px',
    left: '0',
    right: '0',
    textAlign: 'center',
    padding: '0 8px',
  },
  titleFontSize: '14px',
  titleColor: '#ffffff',
  titleTextShadow: '2px 2px 4px rgba(0,0,0,0.8), -1px -1px 2px rgba(0,0,0,0.6)',
  descriptionPosition: {
    bottom: '8px',
    left: '0',
    right: '0',
    textAlign: 'center',
    padding: '0 8px',
  },
  descriptionFontSize: '10px',
  descriptionColor: '#ffffff',
  descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.8), -1px -1px 2px rgba(0,0,0,0.6)',
};

export const cardTypeStyles: CardTypeStyles = {
  paladin: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#ffd700',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(255,215,0,0.3)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#ffffff',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  rogue: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#9370db',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(147,112,219,0.4)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#e8e0f0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  mage: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#00bfff',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 10px rgba(0,191,255,0.4)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#e0f8ff',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  warrior: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#cd5c5c',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(205,92,92,0.4)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#ffe0e0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  ranger: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#90ee90',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(144,238,144,0.3)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#e0ffe0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  priest: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#ffffff',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 10px rgba(255,255,255,0.5)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#f0f0f0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  druid: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#ff8c00',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(255,140,0,0.4)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#fff0e0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  warlock: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#8b008b',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 10px rgba(139,0,139,0.5)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#f0e0f0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  barbarian: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#ff4500',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(255,69,0,0.4)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#ffe8e0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'player-deck': {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#87ceeb',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(135,206,235,0.4)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#e0f0ff',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'wizard-deck': {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#da70d6',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 10px rgba(218,112,214,0.5)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#f8e0f8',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  // Class cards - larger title, centered
  'paladin-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#ffd700',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(255,215,0,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#ffffff',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'rogue-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#9370db',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(147,112,219,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#e8e0f0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'mage-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#00bfff',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(0,191,255,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#e0f8ff',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'warrior-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#cd5c5c',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(205,92,92,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#ffe0e0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'ranger-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#90ee90',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(144,238,144,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#e0ffe0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'priest-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#ffffff',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(255,255,255,0.6)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#f0f0f0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'druid-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#ff8c00',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(255,140,0,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#fff0e0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'warlock-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#8b008b',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(139,0,139,0.6)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#f0e0f0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'barbarian-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#ff4500',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(255,69,0,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#ffe8e0',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  // Bard class
  bard: {
    titlePosition: {
      top: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '0 10px',
    },
    titleFontSize: '14px',
    titleColor: '#dda0dd',
    titleTextShadow: '2px 2px 4px rgba(0,0,0,0.9), 0 0 8px rgba(221,160,221,0.4)',
    descriptionPosition: {
      bottom: '6px',
      left: '0',
      right: '0',
      textAlign: 'center',
      padding: '4px 8px',
    },
    descriptionFontSize: '9px',
    descriptionColor: '#f8e8f8',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'bard-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#dda0dd',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(221,160,221,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#f8e8f8',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
  'wizard-class': {
    titlePosition: { top: '40%', left: '0', right: '0', textAlign: 'center', padding: '0 10px' },
    titleFontSize: '18px',
    titleColor: '#da70d6',
    titleTextShadow: '2px 2px 6px rgba(0,0,0,0.9), 0 0 12px rgba(218,112,214,0.5)',
    descriptionPosition: { bottom: '10px', left: '0', right: '0', textAlign: 'center', padding: '4px 8px' },
    descriptionFontSize: '8px',
    descriptionColor: '#f8e0f8',
    descriptionTextShadow: '1px 1px 3px rgba(0,0,0,0.9)',
  },
};

export function getCardStyle(type: string): CardTypeStyle {
  return cardTypeStyles[type] || defaultStyle;
}
